"project_id": "558549"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
files: [
  {
    "source": "src/HyPlayer.App/Strings/zh-CN/Resources.resw",
    "translation": "src/HyPlayer.App/Strings/%locale%/Resources.resw"
  }
]